### ISSUE TITLE
Field "Query.ok" can only be defined once

### ISSUE THREAD

**Issue by nayaabkhan** [0xR/graphql-transform-federation#1]
# What

The Gateway service throws the following error:

> UnhandledPromiseRejectionWarning: GraphQLSchemaValidationError: Field "Query.ok" can only be defined once.

# When

A field `ok: Boolean` is added to `Query` type when a service does not have any query type defined in its schema. When more than one such services exist, the gateway throws the error.

# Repo

The issue can be reproduced on this branch: https://github.com/nayaabkhan/nexus-federation-example/tree/query-nok

The issue gets resolved when a `Query` is added to the schema: https://github.com/nayaabkhan/nexus-federation-example

With the details out of the way, I would like to thank you for this library. It is going to save a lot of trouble where people find themselves wanting to use Federation with existing services or like me who want to use it with a code-first approach with Nexus/TypeGraphQL. A BIG thank you.

**Comment by nayaabkhan** [comment]
On a deeper investigation, it looks like `Query.ok` may be coming from Nexus itself. If that is the case, happy to close this issue.

**Comment by 0xR** [comment]
Glad you like the library!

Did you figure out the nexus specific issue? It should be possible to modify the nexus schema using a graphql transform: https://www.apollographql.com/docs/graphql-tools/schema-transforms/

You could remove the `ok` field or rename one of the `ok` fields.

**Comment by mac2000** [comment]
There is a problem with schema-transforms which might not be always suitable and needs somehow to incorporate inside graphql-transform-federation

Lets suppose that we following services (aka not federated which will be covered by graphql-transform-federation:

**Accounts**

```gql
type Query {
  accounts: [Account]!
  account(id: ID!): Account # will be used by delegateToSchema
}

type Account {
  id: ID!
  username: String
}
```

**Articles**

```gql
type Query {
  articles: [Article]!
  article(id: ID!): Article # will be used by delegateToSchema
  articlesByAccount(accountId: ID!): [Article]!
  account(id: ID!): Account # will be used by delegateToSchema
}

type Article {
  id: ID!
  # accountId: ID! # hiding original "accountId: ID!" property in favor to "account: Account!"
  account: Account!
  title: String
  body: String
}

type Account {
  id: ID!
  articles: [Article]!
}
```

Second service is trying to be federation ready as much as possible but for resolvers to work we gonna need to have some root resolver for foreign types

My idea here was to name it `account(id: ID!): Account` with a resolver like `account: (_, {id}) => ({id})` then all required reference queries will work as expected, but now we can not connect them both into gateway because there is two `Query.account` fields

Workaround for now is to have some kind of ugly `_articlesGetAccountById(id:ID!): Account` in articles service and delegate to it in federated schema - but it becomes visible in a gateway

@0xR not sure but your suggestion not going to work here because:

1. if I will transform schema (remove Query.account from Articles service) **before** federation transformation - delegation wont work
2. if I will transform schema (remove Query.account from Articles service) **after** federation transfromation - gateway wont work (federation transformation will catch field which we want remove and return it to gateway in _service sdl)

Not sure yet, but to me it seems that without being able to hide certain fields inside federation transformation it wont work

**Comment by mac2000** [comment]
BTW it seems that transform-sdl.ts might be a good place for all this because its generated sdl is what will be visible to gateway and there is already properties for both types and fields, wondering if there will be some kind of `hidden: boolean` property side by side with all others then in my transformation config I will be able to say something like:

```js
{
  Query: {
    extend: true,
    fields: {
      someUnwantedField: {
        hidden: true
      }
    }
  },
  SomeOtherUnwantedType: {
    hidden: true
  },
  // ...
}
```
